name: Python application

on:
  push:
    paths:
      - 'test_naukri_login.py'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Run tests with secrets
      env:
        N_USERNAME: ${{ secrets.N_USERNAME }}
        N_PASSWORD: ${{ secrets.N_PASSWORD }}
        UPDATED_NAME: ${{ secrets.UPDATED_NAME }}
      run: pytest test_naukri_login.py
